"""Edited models

Revision ID: b6a07abc7a84
Revises: b379fce7498a
Create Date: 2023-07-08 09:47:21.132407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a07abc7a84'
down_revision = 'b379fce7498a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_animals_centre_id', 'centres', ['centre_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('age', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('email', existing_type=sa.String(), nullable=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.alter_column('email', existing_type=sa.String(), nullable=True)
        batch_op.alter_column('age', existing_type=sa.Integer(), nullable=True)

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_animals_centre_id', type_='foreignkey')
        batch_op.drop_column('centre_id')

    # ### end Alembic commands ###

